const CONSULTANTS_CODEWARS = {
  cheynemh: "Cheyne Murdoch-Hall",
  smllygrl: "Natalie Lovibond Hodgson",
  "Jinn-T": "Jinn Tsang",
  martynakr: "Martyna Krol",
  Harrisonp365: "Harrison Powell",
  sebzo65: "Sebastian Penedo",
  SGray1255: "Stephen Gray",
  blakelists: "Blake Stickland",
  helexander: "Jeremy Chee",
  sandramyrda: "Sandra Myrda",
  redprakash: "Prakash Poudel",
  Wondermelon98: "Tim Ng",
  YujinOk: "Yujin",
  HowLargeTheTeeth: "Emily Graham",
  b0rgsta: "Andrew Borg",
};
